/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./src/demux1x2_behav.v:12" *)
module demux12_syn(reset, clk, in, classif, push_0, push_1, out0, out1);
  (* src = "./src/demux1x2_behav.v:24" *)
  wire [9:0] _00_;
  (* src = "./src/demux1x2_behav.v:24" *)
  wire [9:0] _01_;
  (* src = "./src/demux1x2_behav.v:24" *)
  wire _02_;
  (* src = "./src/demux1x2_behav.v:24" *)
  wire _03_;
  wire _04_;
  wire [9:0] _05_;
  wire [9:0] _06_;
  (* src = "./src/demux1x2_behav.v:16" *)
  input classif;
  (* src = "./src/demux1x2_behav.v:14" *)
  input clk;
  (* src = "./src/demux1x2_behav.v:15" *)
  input [9:0] in;
  (* src = "./src/demux1x2_behav.v:19" *)
  output [9:0] out0;
  (* src = "./src/demux1x2_behav.v:20" *)
  output [9:0] out1;
  (* src = "./src/demux1x2_behav.v:17" *)
  output push_0;
  (* src = "./src/demux1x2_behav.v:18" *)
  output push_1;
  (* src = "./src/demux1x2_behav.v:13" *)
  input reset;
  assign _06_[6] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[6] : in[6];
  assign _06_[7] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[7] : in[7];
  assign _06_[8] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[8] : in[8];
  assign _06_[9] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[9] : in[9];
  assign _00_[0] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[0] : 1'h0;
  assign _00_[1] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[1] : 1'h0;
  assign _00_[2] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[2] : 1'h0;
  assign _00_[3] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[3] : 1'h0;
  assign _00_[4] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[4] : 1'h0;
  assign _00_[5] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[5] : 1'h0;
  assign _00_[6] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[6] : 1'h0;
  assign _00_[7] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[7] : 1'h0;
  assign _00_[8] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[8] : 1'h0;
  assign _00_[9] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _06_[9] : 1'h0;
  assign _03_ = reset ? (* src = "./src/demux1x2_behav.v:25" *) classif : 1'h0;
  assign _02_ = reset ? (* src = "./src/demux1x2_behav.v:25" *) _04_ : 1'h0;
  assign _05_[0] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[0] : out1[0];
  assign _05_[1] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[1] : out1[1];
  assign _05_[2] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[2] : out1[2];
  assign _05_[3] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[3] : out1[3];
  assign _05_[4] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[4] : out1[4];
  assign _05_[5] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[5] : out1[5];
  assign _05_[6] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[6] : out1[6];
  assign _05_[7] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[7] : out1[7];
  assign _05_[8] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[8] : out1[8];
  assign _05_[9] = classif ? (* src = "./src/demux1x2_behav.v:39|./src/demux1x2_behav.v:33" *) in[9] : out1[9];
  assign _01_[0] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[0] : 1'h0;
  assign _01_[1] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[1] : 1'h0;
  assign _01_[2] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[2] : 1'h0;
  assign _01_[3] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[3] : 1'h0;
  assign _01_[4] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[4] : 1'h0;
  assign _01_[5] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[5] : 1'h0;
  assign _01_[6] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[6] : 1'h0;
  assign _01_[7] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[7] : 1'h0;
  assign _01_[8] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[8] : 1'h0;
  assign _01_[9] = reset ? (* src = "./src/demux1x2_behav.v:25" *) _05_[9] : 1'h0;
  assign _06_[0] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[0] : in[0];
  assign _06_[1] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[1] : in[1];
  assign _06_[2] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[2] : in[2];
  assign _06_[3] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[3] : in[3];
  assign _06_[4] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[4] : in[4];
  assign _06_[5] = classif ? (* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) out0[5] : in[5];
  assign _04_ = ~(* src = "./src/demux1x2_behav.v:34|./src/demux1x2_behav.v:33" *) classif;
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _50_ (
    .C(clk),
    .D(_02_),
    .Q(push_0)
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _51_ (
    .C(clk),
    .D(_03_),
    .Q(push_1)
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out0[0])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _53_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out0[1])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _54_ (
    .C(clk),
    .D(_00_[2]),
    .Q(out0[2])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _55_ (
    .C(clk),
    .D(_00_[3]),
    .Q(out0[3])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _56_ (
    .C(clk),
    .D(_00_[4]),
    .Q(out0[4])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _57_ (
    .C(clk),
    .D(_00_[5]),
    .Q(out0[5])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _58_ (
    .C(clk),
    .D(_00_[6]),
    .Q(out0[6])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _59_ (
    .C(clk),
    .D(_00_[7]),
    .Q(out0[7])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _60_ (
    .C(clk),
    .D(_00_[8]),
    .Q(out0[8])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _61_ (
    .C(clk),
    .D(_00_[9]),
    .Q(out0[9])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _62_ (
    .C(clk),
    .D(_01_[0]),
    .Q(out1[0])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _63_ (
    .C(clk),
    .D(_01_[1]),
    .Q(out1[1])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _64_ (
    .C(clk),
    .D(_01_[2]),
    .Q(out1[2])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _65_ (
    .C(clk),
    .D(_01_[3]),
    .Q(out1[3])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _66_ (
    .C(clk),
    .D(_01_[4]),
    .Q(out1[4])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _67_ (
    .C(clk),
    .D(_01_[5]),
    .Q(out1[5])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _68_ (
    .C(clk),
    .D(_01_[6]),
    .Q(out1[6])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _69_ (
    .C(clk),
    .D(_01_[7]),
    .Q(out1[7])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _70_ (
    .C(clk),
    .D(_01_[8]),
    .Q(out1[8])
  );
  (* src = "./src/demux1x2_behav.v:24" *)
  DFF _71_ (
    .C(clk),
    .D(_01_[9]),
    .Q(out1[9])
  );
endmodule
